
DROP TABLE IF EXISTS `ACTIVITY`;
CREATE TABLE `ACTIVITY`
(
    `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(256) NOT NULL,
    `time` VARCHAR(36) DEFAULT NULL,
    `classify` VARCHAR(36) NOT NULL,
    `views` bigint(20) UNSIGNED DEFAULT 0,
    `poster` TEXT NOT NULL,
    `content` TEXT DEFAULT NULL,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `NEWS`;
CREATE TABLE `NEWS`
(
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(256) NOT NULL,
    `time` VARCHAR(36) DEFAULT NULL,
    `views` bigint(20) UNSIGNED DEFAULT 0,
    `content` TEXT DEFAULT NULL,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

