DROP TABLE IF EXISTS `PAPERS`;
CREATE TABLE `PAPERS`
(
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name` TEXT NOT NULL,
    `author` VARCHAR(1024) NOT NULL,
    `year` VARCHAR(10) NOT NULL,
    `conference` VARCHAR(1024) NOT NULL,
    `link` VARCHAR(256) DEFAULT NULL,
    `synopsis` TEXT DEFAULT NULL,
    `keywords` TEXT DEFAULT NULL,
    `level` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `CHINESEPAPERS`;
CREATE TABLE `CHINESEPAPERS`
(
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name` TEXT NOT NULL,
    `author` VARCHAR(1024) NOT NULL,
    `year` VARCHAR(10) NOT NULL,
    `conference` VARCHAR(1024) NOT NULL,
    `link` VARCHAR(256) DEFAULT NULL,
    `synopsis` TEXT DEFAULT NULL,
    `keywords` TEXT DEFAULT NULL,
    `level` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;