server:
  port: 8088

spring:
  application:
    name: team
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blc?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aabbcc123

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/