server:
  port: 8081

spring:
  application:
    name: team
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://101.43.110.92:3306/blcbackend?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aabbcc123

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://101.43.110.92:8761/eureka/