spring:
  application:
    name: blc-activity-service
  datasource:
    url: jdbc:mysql://localhost:3306/blcact?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aabbcc123
#  sql:
#    init:
#      schema-locations: classpath:sql/blc.sql
#      mode: never
  config:
    activate:
      on-profile: dev

server:
  port: 8084
  session-timeout: 30
  tomcat.max-threads: 1
  tomcat.uri-encoding: UTF-8

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/