spring:
  config:
    activate:
      on-profile: prod
  application:
    name: blc-activity-service
  datasource:
    url: jdbc:mysql://101.43.110.92:3306/blcact?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aabbcc123

server:
  port: 8084
  session-timeout: 30
  tomcat.max-threads: 1
  tomcat.uri-encoding: UTF-8

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://101.43.110.92:8761/eureka/